# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Dependencies
markdown:	kramdown

# Setup
title:            Beyond Expectation
tagline:          'Rambles about geeky things'
description:      >
  This serves as the dumping ground for Paulin's thoughts on maths, statistics and programming.
url:              http://paulinshek.github.io
baseurl:          
commentsystem:    google
disqus:           example

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

author:
  name:           Paulin

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/paulinshek
    desc:         Follow me on twitter

  - icon:         feed
    url:          http://paulinshek.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Paulin Shek
  url:            http://paulinshek.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false


# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
