---
layout: post
title: "Relationship Analysis"
author: "Paulin and Joe"
date: "2016-02-14"
output: md_document
categories: R
---

```{r, echo = FALSE, eval = TRUE}
## General prep
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)

# set default chunk options


# source: http://data.stanford.edu/hcmst
# translate .Rmd files in the _sources dir to .md files in _posts
# if jekyll is installed then it also compiles the site in _site
# use serve = FALSE if you do not have jekyll installed/ don't want to preview the site
# setwd("/home/paulin/Documents/paulinshek.github.io")
# servr::jekyll() 

# ggplot2 theme
library(ggplot2)
# TODO
```

```{r}
## Data prep

# Navigate to where the data lives. Do not put it on github
dataPath <- "/home/paulin/Documents/SomeRLovin/Relationship Prediction/data/HCMST"

# convert the data from sav files (SAS) to RData objects
library(foreign)

# How Couples Stay Together data
hcmst <- as.data.frame(read.spss(file.path(dataPath, "HCMST.sav"))) # waves 1,2,3
hcmst4 <- as.data.frame(read.spss(file.path(dataPath, "HCMSTwave4.sav")))
hcmst5 <- as.data.frame(read.spss(file.path(dataPath, "HCMSTwave5.sav")))

```


```{r, fig.cap="Grey denotes the repondents who declined to answer a follow-up survey, or where not in a relationship in wave 1, in the first place", warning=FALSE}
# TODO: make a dataset which joins the waves together, keeping the columns related to break up at each wave
library(dplyr)
relationshipStatusOverWave <- data.frame(`Original relationship status` = hcmst$qflag, 
                           `Status at wave 2` = hcmst$w2_broke_up, 
                           `Status at wave 3` = hcmst$w3_broke_up, 
                           `Status at wave 4` = hcmst4$w4_broke_up, 
                           `Status at wave 5` = hcmst5$w5_broke_up,
                           check.names = FALSE)

relationshipStatusOverWave <- relationshipStatusOverWave %>% 
  filter_(~`Original relationship status`=="partnered") %>% 
  select(starts_with("Status"))


tempCombine <- function(x){
  x <- as.character(x)
  res <- ifelse(x %in% c("broke up", "partner deceased", "partner passed away"), "Broke up or partner deceased", x)
  res <- ifelse(res=="still together", "Still together", res)
  levels(res) <- c("Still together", "Broke up or partner deceased")
  return(res)
}
relationshipStatusOverWave <- lapply(relationshipStatusOverWave, tempCombine)

N <- length(relationshipStatusOverWave[[1]])
relationshipStatusOverWave <- lapply(relationshipStatusOverWave, as.character)
status <- do.call(c, relationshipStatusOverWave)
names(status) <- NULL
status <- factor(status, levels = c("Still together", "Broke up or partner deceased"))
wave <- rep(2:5, each = N)
longData <- data.frame(Wave = wave, Status = status)


library(ggplot2)
ggplot(data = longData, aes(x = Wave, fill = Status)) + geom_bar() + 
  ggtitle("Barchart to show the relationship status \nof each survey respondent at each wave \nof the survey") + ylab("Count")

```




# Plan!

* Intro
- motivation
- sentence about data

* model
- bit on significant parameters
- "nearly" significant parameters/untestables
- shiny app
- Calibration plots/ other data plots 

* Conclusion















